config/routes.rb
Rails.application.routes.draw do

  resources :tickets
  # root 'login#index'
  resources :login

  root 'login#new'

  #get 'login', to: :new
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #get 'welcome#home'
  # about 

  get 'about', to: 'welcome#about'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  	@users = User.all
  end

  def show

  end

  def new
  end

  def create
  	user = User.find_by(username: params[:username].downcase)
  	if user
  		if user.password == params[:password] && user.username == params[:username]
  			flash[:success] = 'You are logged in.'
  			render "index"
  		else
  			invalid_login
  		end
  	else
  		invalid_login
  	end

  end

  private 
  	def invalid_login
  		flash[:danger] = 'Invald login details'
  		render "new"
  	end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :summary, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def home

	end

	def about

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyItApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<h1> Welcome to Index page </h1>
 <p> In this page you can see the tickets created by you or create a new ticket. </p>


    <%= form_tag :action => :create do %>
 		<p><%= label_tag :Name, 'User Name: ' %>
 		 <%= text_field_tag :Name %><br></p>

 		 <p><%= label_tag :Email, 'Email: ' %>
 		 <%= text_field_tag :Email %><br></p>

 		<p><%= label_tag :Urgency, 'Urgency:' %>
 			<%= text_field_tag :Urgency %><br></p>

 		<p><%= label_tag :Category, 'Category: ' %>
 			<%= text_field_tag :Category %><br></p>

 		<p><%= label_tag :Summary, 'Summary:' %>

 			<%= text_field_tag :Summary %><br></p>

 		<p><%= label_tag :description, 'Description:' %>

 			<%= text_area_tag :description %><br></p>
 				 	
 		<%= submit_tag 'Create ticket' %>
 	<% end %>

app/views/login/new.html.erb
<body>
<div>
	<%= form_tag :action => :create do %>
 		<p><%= label_tag :username, 'Username: ' %></p>
 		<%= text_field_tag :username %><br>

 		<p><%= label_tag :password, 'Password: ' %> </p>
 		<%= password_field_tag :password %><br>
 		<%= submit_tag 'Login' %>
 	<% end %>

</div>
<% flash.each do |key, value| %>
	<%= value %>
<% end %>


 </body>

app/views/login/show.html.erb
h1>Login#show</h1>

<p>Find me in app/views/login/show.html.erb</p>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.summary %></td>
        <td><%= ticket.description %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @ticket.summary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/welcome/about.html.erb
<h1> This is About page </h1>

<%= link_to 'Home ', root_path %>

app/views/welcome/home.html.erb
<h1> This is Homepage </h1>

<%= link_to 'About', about_path %>